### ISSUE TITLE
CoModException

### ISSUE THREAD

**Issue by XakepSDK** [Th3Tr0LLeR/SkinsRestorer---Maro#209] opened 2017-09-12 20:49 UTC
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/src/skinsrestorer/bukkit/skinfactory/UniversalSkinFactory.java#L255
```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:168)
    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:149)
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setOp(CraftPlayer.java:109)
    at skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.updateSkin(UniversalSkinFactory.java:255)
    at skinsrestorer.bukkit.SkinsRestorer$1$1.run(SkinsRestorer.java:159)
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by DoNotSpamPls** [comment] 2017-10-15 11:07
Hello,

We are in the process of fixing this in SkinsRestorer. Can you give us more information, so we can reproduce the bug?
Thanks!

**Comment by games647** [comment] 2017-10-15 11:09
Just don't change the OP status in an async thread. That's (like many other things in the Bukkit API) not thread-safe and therefore should only be modified in the main thread.

**Comment by DoNotSpamPls** [comment] 2017-10-15 16:26
@games647 the problem is, if I move it anywhere else, it doesn't fix the problem which it was added for in the first place - command blocks don't work after skin changes :(

**Comment by XakepSDK** [comment] 2017-10-15 16:40
@DoNotSpamPls this happens, if someone sets OP status asynchronously. This is purely bukkit implementation issue.
Solutions:
1. Don't use that asynchronously
2. Replace PermissibleBase internal HashMap with ConcurrentHashMap
So...

**Comment by DoNotSpamPls** [comment] 2017-10-15 16:49
@XakepSDK i fixed the HashMap thing in [this commit](https://github.com/DoNotSpamPls/SkinsRestorer/commit/25fb92cd17e63c712e3e7a465c157a388bc21ff4). I am working on doing the op thing non-asyncronously

**Comment by XakepSDK** [comment] 2017-10-15 16:55
@DoNotSpamPls 
CoModException happens in craftbukkit side, not in skinsrestorer.

**Comment by DoNotSpamPls** [comment] 2017-10-15 17:15
@XakepSDK 🤦‍♂️
I thought you were talking about SR, since that has a HashMap too. My bad :/
Okay, I'll move the OP thing over.

**Comment by games647** [comment] 2017-10-15 19:11
Nearly everything that interacts with the Bukkit API have to be run in the main thread. You cannot reproduce this, because threading issues don't happen very often and so are hard to find in development environments. 

The only solution is to run the related code on the main thread. You could do this by calling scheduling a new task[¹](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html#runTask-org.bukkit.plugin.Plugin-java.lang.Runnable-). This task will run on the next tick on the main thread. 

Pseudo code:

[...].runTask(plugin, () -> updatePlayer(player.getUniqueId()));

1. The updatePlayer should contain all code that is not thread-safe. This includes **for example**:
    - setOp
    - setVisible
    - canSee
    - updateInventory
    - Inserting the skin data https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/8ae2e3fa61371303c2c71c52ee4f3ca08b3bd047/src/skinsrestorer/bukkit/skinfactory/SkinFactory.java#L30
2. Packet sending in general is thread-safe, but you should make sure that you don't access non thread-safe data (this includes the serialization inside the packet objects). For example the location:
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/8ae2e3fa61371303c2c71c52ee4f3ca08b3bd047/src/skinsrestorer/bukkit/skinfactory/UniversalSkinFactory.java#L93

This could be fixed by making a clone of the relevant objects. Then you have something that isn't shared with the main thread and therfore doesn't cause any conflicts.

3. There are multiple reasons I explicitly used player.getUniqueId() here. The player could disconnect after this one tick (unlikely, but maybe we want to change the task delay later). Then this code forces us to query the player object from the Bukkit API and make a null check (-> online check). Furthermore we don't hold this player reference. This means the player object could be garbage collected after the player disconnected.

**Closed** 2019-01-24 16:08 UTC
Labels: bug, help wanted
